workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.ethioairtime.airtime"  # Change this to your package name
      
    scripts:
      - echo "Starting Android build..."
      - cd android && chmod +x gradlew
      - cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "kalikalikalikali1234567@gmail.com"  # Replace with your email
