name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          java-version: '17'

      # other steps...

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager --verbose "platform-tools" "platforms;android-33" "build-tools;33.0.0"
      - name: stsrt
        run: android/gradle wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Build with Gradle
        run: ./android/gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
